from copy import deepcopy
from pathlib import Path
import xml.etree.ElementTree as ET

EPG = Path(__file__).resolve().parent / 'epg.xml'

JRA = {
    'jra.gch': 'グリーンチャンネル',
    'jra.east': 'JRA EAST',
    'jra.west': 'JRA WEST',
    'jra.hokkaido': 'JRA HOKKAIDO',
}


def set_display_name(channel, text):
    node = channel.find('display-name')
    if node is None:
        node = ET.SubElement(channel, 'display-name')
    node.text = text


def main():
    if not EPG.exists():
        raise SystemExit('epg.xml not found')

    tree = ET.parse(EPG)
    root = tree.getroot()

    # Capture the legacy JRA channels/programmes generated by main_epg_3days.py.
    source_channels = {ch.get('id'): ch for ch in root.findall('channel') if ch.get('id') in JRA}
    source_programmes = {
        base: [p for p in root.findall('programme') if p.get('channel') == base]
        for base in JRA
    }

    # Remove stale split copies first so the script is idempotent.
    split_ids = {f'{base}.hq' for base in JRA} | {f'{base}.lq' for base in JRA}
    for node in list(root):
        if node.tag == 'channel' and node.get('id') in split_ids:
            root.remove(node)
        elif node.tag == 'programme' and node.get('channel') in split_ids:
            root.remove(node)

    # Build HQ/LQ channels and clone the exact same programme data to both.
    for base, display in JRA.items():
        src_ch = source_channels.get(base)
        programmes = source_programmes.get(base, [])
        for quality, label in (('hq', 'HQ'), ('lq', 'LQ')):
            new_id = f'{base}.{quality}'
            if src_ch is not None:
                new_ch = deepcopy(src_ch)
                new_ch.set('id', new_id)
            else:
                new_ch = ET.Element('channel', id=new_id)
            set_display_name(new_ch, f'{display} {label}')
            root.append(new_ch)

            for prog in programmes:
                copied = deepcopy(prog)
                copied.set('channel', new_id)
                root.append(copied)

    # Legacy unsuffixed JRA IDs are no longer exposed after split.
    for node in list(root):
        if node.tag == 'channel' and node.get('id') in JRA:
            root.remove(node)
        elif node.tag == 'programme' and node.get('channel') in JRA:
            root.remove(node)

    ET.indent(tree, space='  ')
    tree.write(EPG, encoding='utf-8', xml_declaration=True)
    print('JRA EPG split complete: 4 services -> 8 HQ/LQ channel IDs')


if __name__ == '__main__':
    main()
